import { useRef } from "react";
import { View, ScrollView, Alert } from "react-native";
import { useRouter, useLocalSearchParams } from "expo-router";
import { Screen } from "../../components/Screen";
import { Title, Subtitle, Body, Caption } from "../../components/Typography";
import { Button } from "../../components/Button";
import { Card } from "../../components/Card";
import { MaterialCommunityIcons, Feather } from "@expo/vector-icons";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export default function Report() {
    const router = useRouter();
    const params = useLocalSearchParams();
    const result = params.result ? JSON.parse(params.result as string) : null;
    const description = params.description as string;
    const duration = params.duration as string;
    const painLevel = params.painLevel as string;
    const hasFever = params.hasFever === "true";
    const hasHistory = params.hasHistory === "true";
    const date = new Date().toLocaleDateString();

    const generateAndSharePdf = async () => {
        try {
            const html = `
        <html>
          <head>
            <style>
              body { font-family: 'Helvetica', sans-serif; padding: 40px; }
              h1 { color: #0f172a; border-bottom: 2px solid #9333ea; padding-bottom: 10px; }
              .section { margin-bottom: 20px; }
              .label { font-weight: bold; color: #475569; }
              .value { color: #1e293b; }
              .disclaimer { margin-top: 40px; padding: 15px; background-color: #f1f5f9; font-size: 12px; color: #64748b; }
              .risk-high { color: #dc2626; font-weight: bold; }
              .risk-moderate { color: #ca8a04; font-weight: bold; }
              .risk-low { color: #16a34a; font-weight: bold; }
            </style>
          </head>
          <body>
            <h1>Linzo Triage Report</h1>
            <p>Date: ${date}</p>
            
            <div class="section">
              <h2>Patient Input</h2>
              <p><span class="label">Symptoms:</span> <span class="value">${description || "N/A"}</span></p>
              <p><span class="label">Duration:</span> <span class="value">${duration || "N/A"}</span></p>
              <p><span class="label">Pain Level:</span> <span class="value">${painLevel}/10</span></p>
              <p><span class="label">Fever:</span> <span class="value">${hasFever ? "Yes" : "No"}</span></p>
              <p><span class="label">Medical History:</span> <span class="value">${hasHistory ? "Yes" : "No"}</span></p>
            </div>

            <div class="section">
              <h2>AI Analysis</h2>
              <p><span class="label">Risk Level:</span> <span class="value ${result?.risk_level === 'High' ? 'risk-high' : result?.risk_level === 'Moderate' ? 'risk-moderate' : 'risk-low'}">${result?.risk_level || "Unknown"}</span></p>
              <p><span class="label">Likely Category:</span> <span class="value">${result?.likely_category || "Unknown"}</span></p>
              <p><span class="label">Confidence Score:</span> <span class="value">${result?.confidence_score}%</span></p>
              <p><span class="label">Reasoning:</span></p>
              <ul>
                ${result?.reasoning?.map((r: string) => `<li>${r}</li>`).join('') || "<li>No reasoning provided</li>"}
              </ul>
            </div>

            <div class="section">
               <h2>Recommendation</h2>
               <p class="value">${result?.recommended_action || "Consult a doctor"}</p>
            </div>

            <div class="disclaimer">
              <strong>DISCLAIMER:</strong> This report is generated by an AI triage system and is NOT a medical diagnosis. The results are for informational purposes mainly to assist in early triage. Always consult a qualified healthcare professional for medical advice, diagnosis, or treatment.
            </div>
          </body>
        </html>
      `;

            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { UTI: ".pdf", mimeType: "application/pdf" });

        } catch (error) {
            Alert.alert("Error", "Failed to generate PDF report.");
        }
    };

    return (
        <Screen safeArea scrollable className="p-6 bg-white" style={{ backgroundColor: '#ffffff' }} contentContainerStyle={{ backgroundColor: '#ffffff' }}>
            <View className="flex-row justify-between items-center mb-6">
                <Title>Triage Report</Title>
                <Caption>{date}</Caption>
            </View>

            <Card className="mb-6">
                <Subtitle className="mb-2">Patient Summary</Subtitle>
                <View className="space-y-2">
                    <View className="flex-row justify-between">
                        <Body className="text-slate-500">Duration</Body>
                        <Body className="font-medium">{duration}</Body>
                    </View>
                    <View className="flex-row justify-between">
                        <Body className="text-slate-500">Pain Level</Body>
                        <Body className="font-medium">{painLevel}/10</Body>
                    </View>
                    <View className="flex-row justify-between">
                        <Body className="text-slate-500">Fever</Body>
                        <Body className="font-medium">{hasFever ? "Yes" : "No"}</Body>
                    </View>
                </View>
            </Card>

            <Card className="mb-6 bg-slate-50 border-slate-100">
                <Subtitle className="mb-2">AI Assessment</Subtitle>
                <View className="flex-row items-center mb-2">
                    <Body className="text-slate-500 mr-2">Risk Level:</Body>
                    <Body className={`font-bold ${result?.risk_level === 'High' ? 'text-red-600' : 'text-purple-600'}`}>
                        {result?.risk_level}
                    </Body>
                </View>
                <View className="flex-row items-center mb-2">
                    <Body className="text-slate-500 mr-2">Category:</Body>
                    <Body className="font-medium">{result?.likely_category}</Body>
                </View>
                <Caption className="text-slate-400 mt-2">
                    Confidence: {result?.confidence_score}%
                </Caption>
            </Card>

            <Button
                title="Download / Share PDF"
                onPress={generateAndSharePdf}
                variant="primary"
                className="mb-4"
            // icon={<Feather name="download" size={20} color="white" />}
            />

            <Button
                title="Done"
                onPress={() => router.replace("/(main)")}
                variant="ghost"
                className="mb-8"
            />
        </Screen>
    );
}
